apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: private-api
  template:
    metadata:
      labels:
        app: private-api
    spec:
      containers:
        - name: private-api
          image: agkj/public-api:latest # actually name error, suppose to be called private 
          env:
            - name: POSTGRES_HOST
              value: "postgres-service.default.svc.cluster.local"  # Postgres service name
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
      restartPolicy: Always
