apiVersion: batch/v1
kind: Job
metadata:
  name: password-rotation
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: postgres-password-rotation
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB    
        command: ["sh", "-c", "psql -h $POSTGRES_HOST -U $POSTGRES_USER -p $POSTGRES_PORT -c \"ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';\""]
      restartPolicy: OnFailure
  backoffLimit: 3
  ttlSecondsAfterFinished: 30
