apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:  # or your storage provider path
    path: /mnt/data/postgres
