apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    POSTGRES_USER: "{{ .Values.postgres.user }}"
    POSTGRES_PASSWORD: "{{ .Values.postgres.password }}" # to be randomly generated
    POSTGRES_DB: "{{ .Values.postgres.database }}"
    POSTGRES_PORT: "{{ .Values.postgres.port }}" 
    
